include make.d/Makefile.header

AIS_NAME             := vbindiff
AIS_VERSION          := 3.0_beta4
AIS_CONFIGURE_OPTS   := --quiet
#AIS_EXPANDED         := t00-lame #. Some tarballs expand into an unexpected directory name
AIS_CHECK            := README
#AIS_BIN              := t00l-kill t00l-resurrect
#AIS_BIN_SUBDIR       := bin
#AIS_SO               := foo bar
#AIS_SO_SUBDIR        := lib
#AIS_PREBUILD_TARGETS := libgak.so libjit.so

include make.d/Makefile.footer
