include make.d/Makefile.header

AIS_NAME       := mozjs
AIS_VERSION    := 24.2.0
AIS_BIN        := js24
AIS_CHECK      := README
AIS_SRC_SUBDIR := js/src
AIS_BIN_SUBDIR := js/src/shell

include make.d/Makefile.footer
