include make.d/Makefile.header

AIS_NAME    := hydra
AIS_VERSION := 8.0
AIS_BIN     := hydra xhydra pw-inspector
AIS_CHECK   := README
AIS_CONFIGURE_OPTS := --with-openssl
AIS_SCM     := https://github.com/vanhauser-thc/thc-hydra.git
AIS_SCM_URI := git

include make.d/Makefile.footer
