#!/usr/bin/env python
import sys
from socket import *
from time import sleep

def put(hostname, path, port, filename, content, translate_bypass=False):
    mysock = socket(AF_INET, SOCK_STREAM)
    try:
        mysock.connect((hostname, port))
    except error, emsg:
        print "Error connecting:", emsg

    request = [
        'PUT %s/%s HTTP/1.1' % (path, filename),
        'Host: %s' % hostname,
        'Connection: TE',
        'TE: trailers',
        'Content-Length: %d' % len(content),
        '',
        content,
        ''
    ]

    try:
        mysock.send('\r\n'.join(request))
    except error, emsg:
        print "Error sending:", emsg

    try:
        response = mysock.recv(128).split("\r\n").pop(0)
    except error, emsg:
        print "Error recving:", emsg

    return response

if __name__ == '__main__':
    fn = 'hi'
    content = 'mewomeow'
    host = sys.argv[1]
    data = open(sys.argv[2])
    i = 0
    for ext in [ 'html', 'htm', 'cfc', 'asp', 'dll', 'exe', 'aspx', 'asmx', 'ashx', 'ascx' ]:
        for path in [_.replace("\n", "") for _ in data.readlines()]:
            i += 1
            d = put(host, path, 80, "%s.%s" % (fn, ext), content)
            print "%03d %64s : %s" % (i, "%s/%s.%s" % (path, fn, ext), d)
            sleep(0.05)
        data.seek(0)
    data.close()
